<DOCTYPE! html>
<head>
		<meta charset="utf-8">
		<title>Contactos Alegra</title>
		<meta name="viewport" content="with=device-with, user-scalable=no, initial-scale=1.0, maximun-scale=1.0, minimun-scale=1.0">
		<link href="<?php echo $this->baseUrl; ?>/css/estilos.css" type="text/css" rel="stylesheet">
		<link href="<?php echo $this->baseUrl; ?>/css/bootstrap.min.css" type="text/css" rel="stylesheet">
		<!-- Para Uso de Iconos -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        
</head>
	<body>
        <header>
        	<nav class="navbar navbar-default">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-1">
							<span class="sr-only">Menu</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a href="#" class="navbar-brand"><img src="<?php echo $this->baseUrl; ?>/img/logo.png" width="120" height="25" alt="header"/></a>
					</div>
					<div class="collapse navbar-collapse" id="navbar-1">
						<ul class="nav navbar-nav">
							<li><a href="<?php echo $this->baseUrl; ?>">Inicio</a></li>
							<li><a href="<?php echo $this->url(array('controller' => 'index','action' => 'add')); ?>">Agregar</a></li>
							<li><a href="https://www.alegra.com/">Pagina Oficial</a></li>
						</ul>
					</div>
				</div>
			</nav>
		</header>
		
		<div class="container-fluid">
			<section class="main row">
				<aside class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
					<h4 class="titulo">CONTACTOS</h4>
					<a href="<?php echo $this->baseUrl; ?>" class="btn btn-block btn-1">TODOS</a>
					<a href="<?php echo $this->url(array('controller' => 'index',
     'action' => 'index', 'view' => 'client')); ?>" class="btn btn-block btn-1">CLIENTES</a>
					<a href="<?php echo $this->url(array('controller' => 'index',
     'action' => 'index', 'view' => 'provider')); ?>"class="btn btn-block btn-1">PROVEEDORES</a>
				</aside>
				<article class="col-xs-12 col-sm-10 col-md-10 col-lg-10 contenido">
					<?php echo $this->layout()->content; ?>
				</article>
			</section>
		</div>

        <script src="<?php echo $this->baseUrl; ?>/js/jquery.js"></script>
        <script src="<?php echo $this->baseUrl; ?>/js/bootstrap.min.js"></script>
        <script src="<?php echo $this->baseUrl; ?>/js/my.js"></script>
	</body>
</html>